name: Sparkle Appcast
description: Generate Sparkle appcast and update enclosure URL to GitHub Releases
inputs:
  products_path:
    required: true
  dist_name:
    required: true
  tag_name:
    required: true
  derived_data_path:
    required: false
    default: DerivedData
runs:
  using: composite
  steps:
    - shell: bash
      run: |
        BIN="${{ inputs.derived_data_path }}/SourcePackages/artifacts/sparkle/Sparkle/bin/generate_appcast"
        if [ ! -x "$BIN" ]; then
          ALT=$(find "$HOME/Library/Developer/Xcode/DerivedData" -path "*/SourcePackages/artifacts/sparkle/Sparkle/bin/generate_appcast" -print -quit 2>/dev/null)
          if [ -x "$ALT" ]; then BIN="$ALT"; fi
        fi
        if [ ! -x "$BIN" ]; then echo "sparkle generate_appcast not found"; exit 1; fi
        "$BIN" "${{ inputs.products_path }}"
    - shell: bash
      run: |
        FILE="${{ inputs.dist_name }}"
        URL="https://github.com/${{ github.repository }}/releases/download/${{ inputs.tag_name }}/$FILE"
        ESCAPED_FILE=$(printf "%s" "$FILE" | sed 's/\./\\./g')
        ESCAPED_URL=$(printf "%s" "$URL" | sed 's/\./\\./g')
        sed -i'' -e "s|https://.*$ESCAPED_FILE|$ESCAPED_URL|" "${{ inputs.products_path }}/appcast.xml"
